# Generated by Django 3.0.6 on 2020-05-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=20)),
                ('asunto', models.CharField(max_length=30)),
                ('post', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('asunto', models.CharField(max_length=30)),
                ('comentario', models.TextField()),
                ('id_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mensajes.Post')),
            ],
        ),
    ]
